language: node_js
node_js:
  - "6.11.3"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - npm install -g polymer-cli
  - npm install
  - bower install
script:
  - polymer build
after_success:
  - echo "Build Completed Successfully.
  - firebase deploy --token $FIREBASE_TOKEN